ales/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'ales'

urlpatterns = [
    re_path(r'^$', views.indexAles, name='indexAles'),
    re_path(r'^services/$', views.pageServices, name='pageServices'),
    re_path(r'^articles/$', views.pageArticles, name='pageArticles'),
    # -------------------------     Articles Pages       --------------------------
    re_path(r'^article-1/$', views.pageArticle_1, name='pageArticle_1'),
    # -------------------------     Services Pages       --------------------------
    re_path(r'^service-1/$', views.pageService_1, name='pageService_1'),
    re_path(r'^bordure-beton-ales/$', views.pageServiceBordureBeton,
            name='pageServiceBordureBeton'),
    re_path(r'^beton-cire-ales/$', views.pageServiceBetonCire,
            name='pageServiceBetonCire'),
    re_path(r'^dalle-beton-ales/$', views.pageServiceDalleBeton,
            name='pageServiceDalleBeton'),
    re_path(r'^beton-decoratif-ales/$',
            views.pageServiceBetonDecoratif, name='pageServiceBetonDecoratif'),
    re_path(r'^beton-desactive-ales/$',
            views.pageServiceBetonDesactive, name='pageServiceBetonDesactive'),
    re_path(r'^beton-imprime-ales/$', views.pageServiceBetonImprime,
            name='pageServiceBetonImprime'),
    re_path(r'^bitume-enrobe-ales/$', views.pageServiceBitumeEnrobe,
            name='pageServiceBitumeEnrobe'),
    re_path(r'^coulage-fondation-ales/$',
            views.pageServiceCoulageFondation, name='pageServiceCoulageFondation'),
    re_path(r'^pavage-dallage-ales/$', views.pageServicePavageDallage,
            name='pageServicePavageDallage'),
    re_path(r'^resine-sol-epoxy-ales/$',
            views.pageServiceResineEpoxy, name='pageServiceResineEpoxy'),
    re_path(r'^terrasse-gres-cerame-ales/$',
            views.pageServiceGresCerame, name='pageServiceGresCerame'),
    re_path(r'^terrasse-pierre-naturelle-ales/$',
            views.pageServicePierreNaturelle, name='pageServicePierreNaturelle'),

    # -------------------------     Thank You Pages       --------------------------
    re_path(r'^thank-you/$', views.thankYouAles, name='thankYouAles'),
    # -------------------------     GDPR Pages       --------------------------
    re_path(r'^mentionslegales/$', views.mentions_lega, name='mentions_lega'),
    re_path(r'^politiquedeconfidentialite/$',
            views.politique_conf, name='politique_conf'),
    re_path(r'^politiquedecookies/$',
            views.politique_cook, name='politique_cook'),
]

mirbeton/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from django.contrib.sitemaps.views import sitemap
from django.conf import settings # new
from django.conf.urls.static import static #new
from siteMain import views
from mirbeton.sitemaps import StaticViewSitemap

sitemaps = { 
        'static': StaticViewSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^siteMain/', include('siteMain.urls', namespace="siteMain")),
    re_path(r'^antony/', include('antony.urls', namespace="antony")),
    re_path(r'^ales/', include('ales.urls', namespace="ales")),
    re_path(r'^cholet/', include('cholet.urls', namespace="cholet")),
    re_path(r'^chatellerault/',
            include('chatellerault.urls', namespace="chatellerault")),
    re_path(r'^poitiers/',
            include('poitiers.urls', namespace="poitiers")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

poitiers/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'poitiers'

urlpatterns = [
    re_path(r'^$', views.indexPoitiers, name='indexPoitiers'),
    re_path(r'^services/$', views.pageServices, name='pageServices'),
    re_path(r'^articles/$', views.pageArticles, name='pageArticles'),
    # -------------------------     Articles Pages       --------------------------
    re_path(r'^article-1/$', views.pageArticle_1, name='pageArticle_1'),
    # -------------------------     Services Pages       --------------------------
    re_path(r'^service-1/$', views.pageService_1, name='pageService_1'),
    re_path(r'^bordure-beton-poitiers/$', views.pageServiceBordureBeton,
            name='pageServiceBordureBeton'),
    re_path(r'^beton-cire-poitiers/$', views.pageServiceBetonCire,
            name='pageServiceBetonCire'),
    re_path(r'^dalle-beton-poitiers/$', views.pageServiceDalleBeton,
            name='pageServiceDalleBeton'),
    re_path(r'^beton-decoratif-poitiers/$',
            views.pageServiceBetonDecoratif, name='pageServiceBetonDecoratif'),
    re_path(r'^beton-desactive-poitiers/$',
            views.pageServiceBetonDesactive, name='pageServiceBetonDesactive'),
    re_path(r'^beton-imprime-poitiers/$', views.pageServiceBetonImprime,
            name='pageServiceBetonImprime'),
    re_path(r'^bitume-enrobe-poitiers/$', views.pageServiceBitumeEnrobe,
            name='pageServiceBitumeEnrobe'),
    re_path(r'^coulage-fondation-poitiers/$',
            views.pageServiceCoulageFondation, name='pageServiceCoulageFondation'),
    re_path(r'^pavage-dallage-poitiers/$', views.pageServicePavageDallage,
            name='pageServicePavageDallage'),
    re_path(r'^resine-sol-epoxy-poitiers/$',
            views.pageServiceResineEpoxy, name='pageServiceResineEpoxy'),
    re_path(r'^terrasse-gres-cerame-poitiers/$',
            views.pageServiceGresCerame, name='pageServiceGresCerame'),
    re_path(r'^terrasse-pierre-naturelle-poitiers/$',
            views.pageServicePierreNaturelle, name='pageServicePierreNaturelle'),
    re_path(r'^terrasse-pierre-naturelle-gres-cerame-poitiers/$',
            views.pageServicePierreNaturelleGresCerame, name='pageServicePierreNaturelleGresCerame'),
    re_path(r'^amenagement-exterieur-poitiers/$',
            views.pageServiceAmenagementExterieur, name='pageServiceAmenagementExterieur'),
    re_path(r'^terrasse-bois-poitiers/$',
            views.pageServiceTerrasseBois, name='pageServiceTerrasseBois'),
    re_path(r'^travaux-second-oeuvre-poitiers/$',
            views.pageServiceTravauxSecondOeuvre, name='pageServiceTravauxSecondOeuvre'),
    re_path(r'^travaux-gros-oeuvre-poitiers/$',
            views.pageServiceTravauxGrosOeuvre, name='pageServiceTravauxGrosOeuvre'),
    re_path(r'^terrasse-carrelage-poitiers/$',
            views.pageServiceTerrasseCarrelage, name='pageServiceTerrasseCarrelage'),
    re_path(r'^terrasse-allee-pavee-poitiers/$',
            views.pageServiceTerrasseAlleePavee, name='pageServiceTerrasseAlleePavee'),
    re_path(r'^terrasse-beton-pierre-poitiers/$',
            views.pageServiceTerrasseBetonPierre, name='pageServiceTerrasseBetonPierre'),
    re_path(r'^entree-garage-poitiers/$',
            views.pageServiceEntreeGarage, name='pageServiceEntreeGarage'),

    # -------------------------     Thank You Pages       --------------------------
    re_path(r'^thank-you/$', views.thankYouPoitiers,
            name='thankYouPoitiers'),
    # -------------------------     Promotion Pages       --------------------------
    re_path(r'^promotion-du-printemps/$',
            views.pagePoitiersPromotionDuPrintemps, name='pagePoitiersPromotionDuPrintemps'),
    re_path(r'^promotion-du-printemps-thank-you/$', views.thankYouPoitiersPromotionDuPrintemps,
            name='thankYouPoitiersPromotionDuPrintemps'),
    # -------------------------     GDPR Pages       --------------------------
    re_path(r'^mentionslegales/$', views.mentions_lega, name='mentions_lega'),
    re_path(r'^politiquedeconfidentialite/$',
            views.politique_conf, name='politique_conf'),
    re_path(r'^politiquedecookies/$',
            views.politique_cook, name='politique_cook'),
]

poitiers/models.py
from queue import Empty
from django.db import models

# Create your models here.


class Lead(models.Model):
    work_type = models.CharField(max_length=255, default='other')
    surface = models.CharField(max_length=255)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255, default='null')
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=10)
    message = models.CharField(max_length=3000)

poitiers/forms.py
from django.db.models import fields
from django import forms
from . import models
from django.core import validators

work_type_choices = [('path', 'Allée'), ('stairs', 'Escaliers'),
                     ('slab', 'Dalles'), ('other', 'Autre')]

surface_choices = [('under5m2', 'Inférieur à 5m²'), ('under10m2',
                                                     'Entre 5m² et 10m²'), ('above10m2', 'Supérieur à 10m²')]


class LeadConsultForm(forms.ModelForm):
    lead_consult_form = forms.BooleanField(
        widget=forms.HiddenInput, initial=True)

    class Meta:
        model = models.Lead
        fields = ('work_type', 'surface', 'first_name',
                  'last_name', 'email', 'phone', 'zipcode')

    work_type = forms.CharField(widget=forms.RadioSelect(choices=work_type_choices, attrs={
                                'class': 'subsection-prospect-form--wrapper-form__form--wrapper-radio__wrap-choices'}), required=False)

    surface = forms.CharField(widget=forms.Select(choices=surface_choices, attrs={
                              'class': 'subsection-prospect-form--wrapper-form__form--wrapper-select__wrap-choices'}), required=False)
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'subsection-prospect-form--wrapper-form__form--firstname', 'area-required': 'true', 'data-msg-required': 'Merci d\'indiquer votre prenom s\'il vous plaît', 'placeholder': " PRENOM "}), label='Prenom')

    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'subsection-prospect-form--wrapper-form__form--lastname', 'area-required': 'true', 'data-msg-required': 'Merci d\'indiquer votre nom s\'il vous plaît', 'placeholder': " NOM "}), label='Nom')

    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'subsection-prospect-form--wrapper-form__form--email', 'area-required': 'true', 'data-msg-required': 'Merci d\'indiquer votre email s\'il vous plaît', 'placeholder': " EMAIL "}), label='Email')

    phone = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'subsection-prospect-form--wrapper-form__form--phone', 'area-required': 'true', 'data-msg-required': 'Merci d\'indiquer votre numéro de téléphone s\'il vous plaît', 'placeholder': " TELEPHONE "}), label='Téléphone')

    zipcode = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'subsection-prospect-form--wrapper-form__form--zipcode', 'area-required': 'true', 'data-msg-required': 'Merci d\'indiquer votre code postal s\'il vous plaît', 'placeholder': " CODE POSTAL"}), label='Code Postal')

templates/poitiers/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block meta_description_block %}
    {% endblock %}
    
    <!-- OneTrust Cookies Consent Notice start for www.mirbeton.com -->
<!-- <script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="4ceabdd4-68b5-43db-9236-bfcca562217d-test" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script> -->
<!-- OneTrust Cookies Consent Notice end for www.mirbeton.com -->
    
<!-- Google tag (gtag.js) -->
<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=G-XW54WD06VS"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XW54WD06VS');
</script> -->

   <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-5MZ8W5R');</script>
    <!-- End Google Tag Manager -->

    
    <!-- Meta Domain Verification
    <meta name="facebook-domain-verification" content="eayaxlcnlqpp7hwik7lep6yj84dz0i" />
    Meta Pixel Code
    <script>
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '789597352211323');
    fbq('track', 'PageView');

    </script>
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=789597352211323&ev=PageView&noscript=1"
    /></noscript>
    End Meta Pixel Code -->
    <!-- Main Style -->
    <link rel="stylesheet" href="{% static 'css/main-style.css'%}">
    <!-- Slick Style -->
    <link rel="stylesheet" href="{% static 'slick/slick.css'%}">
    <link rel="stylesheet" href="{% static 'slick/slick-theme.css'%}">
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <!-- Fonts II-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zilla+Slab:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400;1,500;1,600&display=swap" rel="stylesheet">
    {% block title_block %}
    {% endblock %}
    <!-- Icon Link -->
    <link rel = "shortcut icon" href = "{% static 'img/mirbeton-black.png' %}" type = "image/x-icon">
</head>
<body>
 <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5MZ8W5R"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <!-- <div class="section-top-banner">
        <p class="section-top-banner--para">
            <a href="#prospect-form"><span>Pour la nouvelle année!</span>Le plan de votre aménagement pour seulement 99 &euro; avec votre devis! <span>Offre valable jusqu'au 31/03/2023</span></a>
        </p>
        
        <input type="checkbox" class="section-top-banner--checkbox" id="top-banner-toggle">
        <label class="section-top-banner--label" for="top-banner-toggle"><span class="section-top-banner--label__span"></span></label>
    </div> -->

    <div class="section-top-cta">
        <div class="section-top-cta--wrap-cta">
            <svg class="section-top-cta--wrap-cta__link--symbol">
                <use href="{% static 'img/sprite.svg' %}#phonea"></use>
            </svg>
            <a href="tel:0664584884" class="section-top-cta--wrap-cta__phonelink">
               <span>06 64 58 48 84 - 24h</span>
            </a>
         </div>
        <div class="section-top-cta--wrap-cta">
            <svg class="section-top-cta--wrap-cta__link--symbol">
                <use href="{% static 'img/sprite.svg' %}#devis"></use>
            </svg>
            <a href="#prospect-form" class="section-top-cta--wrap-cta__link">
                <span>Devis Gratuit</span>
            </a>
         </div>
    </div>

    <div class="section-navigation">
        <a href="{% url 'poitiers:indexPoitiers'%}" class="section-navigation--wrapper-logo">
            <!-- <svg class="section-navigation--wrapper-logo__logo">
                <use href="{% static 'img/sprite.svg' %}#logo-mirbeton-white"></use>
            </svg> -->
            <img class="section-navigation--wrapper-logo__logo"  src="{% static 'img/mirbeton-white.png'%}" alt="logo">
        </a>

        <div class="section-navigation--checkbox-wrap">
            <input type="checkbox" class="section-navigation--checkbox-wrap__checkbox" id="side-nav-toggle">
            <label class="section-navigation--checkbox-wrap__label"for="side-nav-toggle"><span class="section-navigation--checkbox-wrap__label--span"></span></label>
            <div class="section-navigation--checkbox-wrap__nav-background">
                &nbsp;
            </div>
        </div>
        
        <div class="section-navigation--wrapper-side-nav">
            <div class="section-navigation--wrapper-side-nav__head">
                <div class="section-navigation--wrapper-side-nav__head--wrapper-logo">
                    <a href="{% url 'poitiers:indexPoitiers'%}" >
                      <svg class="section-navigation--wrapper-side-nav__head--wrapper-logo__logo">
                            <use href="{% static 'img/sprite.svg' %}#logo-mirbeton-black"></use>
                        </svg>
                        <!-- <img class="section-navigation--wrapper-side-nav__head--wrapper-logo__logo"  src="/mirbeton/up/img/mirbeton-white.png" alt="logo"> -->
                    </a>
                </div>
                <div class="section-navigation--wrapper-side-nav__head--checkbox-wrap">
                    <!-- <input type="checkbox" class="section-navigation--wrapper-side-nav__head--checkbox-wrap__checkbox" id="sidenav-toggle"> -->
                    <label class="section-navigation--wrapper-side-nav__head--checkbox-wrap__label"for="side-nav-toggle"><span class="section-navigation--wrapper-side-nav__head--checkbox-wrap__label--span"></span></label>
                </div>
            </div>
            <div class="section-navigation--wrapper-side-nav__body">
                <ul class="section-navigation--wrapper-side-nav__body--links">
                    <li class="section-navigation--wrapper-side-nav__body--links__item"><a href="{% url 'poitiers:indexPoitiers'%}" >accueil</a></li>
                    <li class="section-navigation--wrapper-side-nav__body--links__item"><a href="{% url 'poitiers:pageServices'%}">services</a></li>
                    <li class="section-navigation--wrapper-side-nav__body--links__item"><a href="{% url 'poitiers:pageArticles'%}">articles</a></li>
                    <li class="section-navigation--wrapper-side-nav__body--links__wrap-cta">
                      <a href="#prospect-form" class="section-navigation--wrapper-side-nav__body--links__wrap-cta--link">
                      <span>Devis Gratuit</span>
                      </a>
                    </li>
                    <li class="section-navigation--wrapper-side-nav__body--links__wrap-cta">
                      <a href="#prospect-form" class="section-navigation--wrapper-side-nav__body--links__wrap-cta--link">
                      <span>06 64 58 48 84</span>
                      </a>
                    </li>
                </ul> 
            </div>  
        </div>

        <div class="section-navigation--wrapper-nav">
            <div class="section-navigation--wrapper-nav__wrapper-logo">
                <a href="{% url 'poitiers:indexPoitiers'%}" >
                    <!-- <svg class="section-navigation--wrapper-nav__wrap-symbol--symbol">
                        <use href="{% static 'img/sprite.svg' %}#logo-mirbeton-black"></use>
                    </svg> -->
                    <img class="section-navigation--wrapper-nav__wrapper-logo--logo"  src="{% static 'img/mirbeton-white.png'%}" alt="logo">
                </a>
            </div>
            <ul class="section-navigation--wrapper-nav__links">
                      <li class="section-navigation--wrapper-nav__links--item"><a href="{% url 'poitiers:indexPoitiers'%}" >accueil</a></li>
                      <li class="section-navigation--wrapper-nav__links--item"><a href="{% url 'poitiers:pageServices'%}">services</a></li>
                      <li class="section-navigation--wrapper-nav__links--item"><a href="{% url 'poitiers:pageArticles'%}">articles</a></li>
                      <li class="section-navigation--wrapper-nav__links--wrap-cta">
                        <a href="#prospect-form" class="section-navigation--wrapper-nav__links--wrap-cta__link">
                        <span>Devis Gratuit</span>
                        </a>
                      </li>
                      <li class="section-navigation--wrapper-nav__links--wrap-cta">
                        <a href="tel:0664584884" class="section-navigation--wrapper-nav__links--wrap-cta--link">
                        <span>06 64 58 48 84</span>
                        </a>
                      </li>          
            </ul> 
        </div>
    </div>

{% block body_block %}
{% endblock %}
<div class="section-footer">
    <a href="{% url 'poitiers:indexPoitiers'%}" class="section-footer--wrapper-logo">
     <!-- <svg class="section-footer--wrapper-symbol--symbol">
            <use href="{% static 'img/sprite.svg' %}#logo-mirbeton-white"></use>
     </svg> -->
     <img class="section-footer--wrapper-logo__logo"  src="{% static 'img/mirbeton-white.png'%}" alt="logo">
    </a>
    <div class="section-footer--wrapper-content">
        <div class="section-footer--wrapper-content__coord">
            <!-- <h2>mir beton</h2> -->
            <div class="wrap-coord">
                <svg class="wrap-coord--symbol">
                    <use href="{% static 'img/sprite.svg' %}#phonea"></use>
                </svg>
                <a href="tel:0664584884" class="wrap-coord--text">
                   <span>06 64 58 48 84 - 24h</span>
                </a>
            </div>
            <div class="wrap-coord">
                <svg class="wrap-coord--symbol">
                    <use href="{% static 'img/sprite.svg' %}#email"></use>
                </svg>
                <a href="#" class="wrap-coord--text" id="mail-address">
                   <span>mirbetonfrance@gmail.com</span>
                </a>
            </div>
        </div>
    </div>
    <ul class="section-footer--wrapper-links">
        <li class="section-footer--wrapper-links__item"><a href="{% url 'poitiers:politique_conf'%}">
            Potitique de confidentialité</a>
        </li>
        <li class="section-footer--wrapper-links__item"><a href="{% url 'poitiers:mentions_lega'%}">Mentions légales</a></li>
        <li class="section-footer--wrapper-links__item"><a href="{% url 'poitiers:politique_cook'%}">Politique de cookies</a></li>
        <li class="section-footer--wrapper-links__wrap-symbol"><a href="#" >
            <svg class="section-footer--wrapper-links__wrapsymbol--symbol">
                <use href="{% static 'img/sprite.svg' %}#facebook"></use>
            </svg></a>
        </li>
        <!-- <li class="section-footer--wrapper-links__wrap-symbol"><a href="#" >
            <svg class="section-footer--wrapper-links__wrapsymbol--symbol">
                <use href="{% static 'img/sprite.svg' %}#instagram"></use>
            </svg></a>
        </li>
        <li class="section-footer--wrapper-links__wrap-symbol"><a href="#" >
            <svg class="section-footer--wrapper-links__wrapsymbol--symbol">
                <use href="{% static 'img/sprite.svg' %}#pinterest"></use>
            </svg></a>
        </li> -->
    </ul> 
    <p class="section-footer--wrapper-copyright">Copyright &copy; 2022 Lead Insight Marketing all right reserved</p>
</div>

    <!-- JQuery - JS-->
    <script src="{% static 'js/jquery.js'%}"></script>

    <!-- Slick - JS-->
    <script type="text/javascript" src="{% static 'slick/slick.min.js'%}"></script>
    <script src="{% static 'js/slick-setting-reviews.js'%}" ></script>
    <script  src="{% static 'js/slick-setting-articles.js'%}"></script>
    <script  src="{% static 'js/slick-setting-gallery-bis.js'%}"></script>

    <!-- Main - JS-->
    <script src="{% static 'js/main-style.js'%}"></script>
    
    <!-- DataLayer - JS-->
    <script src="{% static 'js/datalayer.js'%}"></script>


    </body>
</html>